### ISSUE TITLE
[BUG] Corrupted instance file (generate command)

### ISSUE THREAD

**Issue by MireilleBF** [ROCKFlows/FromMLWFConfigurationToBPMN#121]
**Describe the bug**
The generated BPMN Instance diagram is corrupted. See image.

**To Reproduce**
Steps/Commands used to reproduce the behavior:
String metaWFPATH = "../BPMN-Models/FeatureBasedMetaWF.bpmn2";
String outputWFPATH = "../BPMN-Models";
File fin = new File(metaWFPATH);
File fout = new File(outputWFPATH);
factory = new InstanceFactoryImpl(fin);
factory.getWFInstance(fout);

**Expected behavior**
When opening the resulting file with BPMN Editor, we should not have to repair the diagram.

**Screenshots or Additional files**
<img width="553" alt="i_ 2020-07-11 à 19 43 23" src="https://user-images.githubusercontent.com/18258429/87230513-e44af700-c3b0-11ea-9d19-988cf5e2cdd3.png">

**Desktop (please complete the following information):**
 - BPMN graphical modeling tool: [e.g. Eclipse BPMN2 Modeler]

**Comment by NicolasLacroix** [comment]
Can you give the implied file so I can try to reproduce the error ?
