### ISSUE TITLE
[BUG] Remove the Unmanaged feature if it has no child

### ISSUE THREAD

**Issue by MireilleBF** [ROCKFlows/FromMLWFConfigurationToBPMN#124]
**Describe the bug**
When I merge a metaworkflow that contains a new task,
the new task appears as a child of Steps and a feature Unmanaged is added without any children

**To Reproduce**
I write a test for that.

**Expected behavior**
Evaluating_step should appear as a child of Steps, being abstract, and unManaged should not be generated.

**Screenshots or Additional files**
Before 
![before](https://user-images.githubusercontent.com/18258429/87303160-fa70c880-c512-11ea-9614-e38e15b507a7.png)

Workflow
![BasicMetaWF](https://user-images.githubusercontent.com/18258429/87303181-02c90380-c513-11ea-9552-46a62d9d6ed1.png)

After
![after](https://user-images.githubusercontent.com/18258429/87303195-09f01180-c513-11ea-8e0b-97b6adb79c65.png)

**Additional context**

**Comment by NicolasLacroix** [comment]
I generated the **Unmanaged** node by default in case of it would be needed later but if you prefer, I can generate it when required and delete it when it has no child.

**Comment by NicolasLacroix** [comment]
I merged (#133) the fix. Can you check if it is fixed for you ?

**Comment by MireilleBF** [comment]
Totally OK
