### ISSUE TITLE
[BUG] Referencing a missing meta-feature (merge --instance)

### ISSUE THREAD

**Issue by MireilleBF** [ROCKFlows/FromMLWFConfigurationToBPMN#132]
**Describe the bug**
One metatask is  silently lost

**To Reproduce**
IN TestInstanceSampleMerge
testBasicSampleUsingCommandLine()
Here is the initial FM
![basicFM](https://user-images.githubusercontent.com/18258429/87591169-37da7f00-c6e8-11ea-8e7c-2726ddaa3a6d.png)

Here is the instance WF
![BasicWF_instance00](https://user-images.githubusercontent.com/18258429/87591184-3dd06000-c6e8-11ea-8ac7-ad1917540d7d.png)
where
![image](https://user-images.githubusercontent.com/18258429/87591260-53de2080-c6e8-11ea-82b4-3e065c1a3a3a.png)

Here is the resulting FM
![resultingFM](https://user-images.githubusercontent.com/18258429/87591389-8851dc80-c6e8-11ea-9be0-95d698eae800.png)

**Expected behavior**
- At least generate a warning.
- Better generate Evaluating_10Flod as unManaged and the same for Evaluating_step
- Even better generate Evaluating_10Flod as a child of Evaluating_step and add a warning

**Comment by NicolasLacroix** [comment]
I merged (#133) the fix. Can you check if it is fixed for you ?

**Comment by MireilleBF** [comment]
Yes, it's OK.
If possible could you emit a warning because Evaluating_step is an unknown meta-feature?
