### ISSUE TITLE
Proposal to improve Readme and some bugs detected

### ISSUE THREAD

**Issue by MireilleBF** [ROCKFlows/FromMLWFConfigurationToBPMN#74]
**Overview** 

- [x]  1 => The ml2wf project aims at helping Data Scientists to create their workflows in the BPMN standard from a FeatureModel and to capitalize on their knowledge in this FeatureModel from new BPMN workflows. 
- [x]  4= >Furthermore, it will allow data specialists to reduce meta-learning space and, over time, automate the creation of workflows tailored to a given time series anomaly detection problem.

**Put an example for generate**

- [x] java -jar ml2wf.jar -g -i ../src/test/resources/wf_meta/simple_wf.bpmn -o output -v 7

For information, here is the trace
18:05:09.798 [main] INFO  com.ml2wf.util.XMLManager - Preprocessing file : simple_wf.bpmn...
18:05:09.827 [main] INFO  com.ml2wf.generation.InstanceFactoryImpl - Starting the Workflow instatiation...
18:05:09.835 [main] INFO  com.ml2wf.generation.InstanceFactoryImpl - Instantiation finished.
18:05:09.835 [main] INFO  com.ml2wf.util.XMLManager - Saving file at location : output/simple_wf_instance.bpmn...
18:05:09.841 [main] FATAL com.ml2wf.cmd.Generate - Can't instantiate the WorkFlow.

- [x] Output should exit, tell it

- [x]  The message isn't clear. I've guessed. We need to make it clearer.

- [x] It fails silently if not verbose. Set at least a warning telling it fails.
- [x] show the resulting trace 

Pour information

mbp-de-mireille:target blay$ ls -la output
total 16
drwxr-xr-x   3 blay  staff    96 14 jui 18:06 .
drwxr-xr-x  12 blay  staff   384 14 jui 18:06 ..
-rw-r--r--   1 blay  staff  5572 14 jui 18:06 simple_wf_instance.bpmn

**Merge**
java -jar ml2wf.jar -m -i ./output/simple_wf_instance.bpmn -o output -v 7
18:17:41.615 [main] INFO  com.ml2wf.util.XMLManager - Preprocessing file : output...
[Fatal Error] :1:1: Content is not allowed in prolog.
18:17:41.664 [main] FATAL com.ml2wf.cmd.Merge - Can't merge the Workflow with the FeatureModel.

- [x] Please allow us to give the link to the featureModel.

I'm stopping because I'm not able to specify the featureModel.

ref : #75

**Comment by NicolasLacroix** [comment]
For the merge command, the expected **-o** argument is the **FeatureModel path** (not the output directory containing the FM). I think that this is the cause of the last issue. I will try to explicit it in the documentation.

**Comment by NicolasLacroix** [comment]
Considering the generation issue, does the simple_wf_instance.bpmn is valid when you open it ?
It is strange that the result file is created if the instantiation failed.
